// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Stateless.Workflow.Features.RestaurantOrders
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RestaurantOrderHandlingFeature : Xunit.IClassFixture<RestaurantOrderHandlingFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RestaurantOrders.feature"
#line hidden
        
        public RestaurantOrderHandlingFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Restaurant order handling", "\tIn order to make customers happy\r\n\tAs a reataurant manager\r\n\tI want to all emplo" +
                    "yess follow the same procedure", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(RestaurantOrderHandlingFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Customer arrives to empty restaurant")]
        [Xunit.TraitAttribute("FeatureTitle", "Restaurant order handling")]
        [Xunit.TraitAttribute("Description", "Customer arrives to empty restaurant")]
        [Xunit.TraitAttribute("Category", "happypath")]
        public virtual void CustomerArrivesToEmptyRestaurant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Customer arrives to empty restaurant", new string[] {
                        "happypath"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("customer has arrived to restaurant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("there are free tables available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("waiter provides a table to the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("waiter starts to wait for order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Customer arrives to full restaurant")]
        [Xunit.TraitAttribute("FeatureTitle", "Restaurant order handling")]
        [Xunit.TraitAttribute("Description", "Customer arrives to full restaurant")]
        [Xunit.TraitAttribute("Category", "happypath")]
        public virtual void CustomerArrivesToFullRestaurant()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Customer arrives to full restaurant", new string[] {
                        "happypath"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("customer has arrived to restaurant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.And("there are no tables available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.When("waiter rejects customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("customer leaves restaurant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RestaurantOrderHandlingFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RestaurantOrderHandlingFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
